# Site settings
title: "Jetson & Isaac Sim HiL Series"
description: "A technical guide to Hardware-in-the-Loop robotics."
baseurl: "/rv-rs-jetson_isaacsim_HiL.github.io" 
url: "https://Filoktimon.github.io"

# Minima Theme Footer Fix
author: "Filoktimon"
email: "your-email@example.com"
twitter_username: 
github_username:  Filoktimon
linkedin_school_name: "Filoktimon Repoulias"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation (for your Sidebar/Header)
header_pages:
  - index.md
  - prerequisites.md
  - part1-hardware.md
  - part2-docker.md
  - part3-networking.md
  - part4-execution.md
